name: ServerPatch
version: '1.3.1'
main: me.rowanscripts.doublelife.DoubleLife
api-version: 1.19
authors: [ Rowan, CarrotC ]
description: dw about it
website: https://github.com/RowwYourBoat

commands:
  serverpatch:
    description: Prefix to all administrative Server Patch related commands
    usage: /serverpatch
    aliases:
      - serverpatch